language: c
compiler:
  - clang
  - gcc
install:
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug
  - make
  - make test
after_success:
  - make coverage
  - bash <(curl -s https://codecov.io/bash)
  - lcov --compat-libtool --directory . --capture --output-file coverage.info
  - coveralls-lcov coverage.info
